export const movieDeck = [
  "GenZ-card1",
  "GenZ-card2",
  "JustCause3-card1",
  "JustCause3-card2",
  "JustCause4-card1",
  "JustCause4-card2",
  "MadMax-card1",
  "MadMax-card2",
  "Rage2-card1",
  "Rage2-card2",
  "SecondExtinction-card1",
  "SecondExtinction-card2",
  "theHunter-card1",
  "theHunter-card2",
  "TheHunter2-card1",
  "TheHunter2-card2",

]

export const fruitsDeck = [
  "apple-card1",
  "apple-card2",
  "bananas-card1",
  "bananas-card2",
  "lime-card1",
  "lime-card2",
  "greenple-card1",
  "greenple-card2",
  "mango-card1",
  "mango-card2",
  "watermelon-card1",
  "watermelon-card2",
  "pineapple-card1",
  "pineapple-card2",
  "orange-card1",
  "orange-card2",
]

export const carDeck = [
  "micro-card1",
  "micro-card2",
  "mordern-card1",
  "mordern-card2",
  "muscle-card1",
  "muscle-card2",
  "offroad-card1",
  "offroad-card2",
  "pickup-card1",
  "pickup-card2",
  "police-card1",
  "police-card2",
  "sports-card1",
  "sports-card2",
  "trans-card1",
  "trans-card2",
]

export const animalsDeck = [
  "antelop-card1",
  "antelop-card2",
  "bull-card1",
  "bull-card2",
  "chamelon-card1",
  "chamelon-card2",
  "fish-card1",
  "fish-card2",
  "parrot-card1",
  "parrot-card2",
  "tiger-card1",
  "tiger-card2",
  "turtule-card1",
  "turtule-card2",
  "zebra-card1",
  "zebra-card2",
]

export const gemsDeck = [
  "img1-card1",
  "img1-card2",
  "img2-card1",
  "img2-card2",
  "img3-card1",
  "img3-card2",
  "img4-card1",
  "img4-card2",
  "img5-card1",
  "img5-card2",
  "img6-card1",
  "img6-card2",
  "img7-card1",
  "img7-card2",
  "img8-card1",
  "img8-card2",
]