export const words = [
    { word: "addition", hint: "The process of adding numbers" },
    { word: "meeting", hint: "Event in which people come together" },
    { word: "number", hint: "Math symbol used for counting" },
    { word: "exchange", hint: "The act of trading" },
    { word: "canvas", hint: "Piece of fabric for oil painting" },
    { word: "garden", hint: "Space for planting flower and plant" },
    { word: "position", hint: "Location of someone or something" },
    { word: "feather", hint: "Hair like outer covering of bird" },
    { word: "comfort", hint: "A pleasant feeling of relaxation" },
    { word: "tongue", hint: "The muscular organ of mouth" },
    { word: "expansion", hint: "The process of increase or grow" },
    { word: "country", hint: "A politically identified region" },
    { word: "group", hint: "A number of objects or persons" },
    { word: "taste", hint: "Ability of tongue to detect flavour" },
    { word: "store", hint: "Large shop where goods are traded" },
    { word: "field", hint: "Area of land for farming activities" },
    { word: "friend", hint: "Person other than a family member" },
    { word: "pocket", hint: "A bag for carrying small items" },
    { word: "needle", hint: "A thin and sharp metal pin" },
    { word: "expert", hint: "Person with extensive knowledge" },
    { word: "statement", hint: "A declaration of something" },
    { word: "second", hint: "One-sixtieth of a minute" },
    { word: "library", hint: "Place containing collection of books" },
    { word: "adventure", hint: "An unusual and exciting experience" },
    { word: "biology", hint: "The science of life and living organisms" },
    { word: "chemistry", hint: "The study of substances and their properties" },
    { word: "dinosaur", hint: "A large extinct reptile" },
    { word: "eclipse", hint: "An event where one celestial body blocks another" },
    { word: "fossil", hint: "Preserved remains of ancient organisms" },
    { word: "galaxy", hint: "A large system of stars, gas, and dust" },
    { word: "horizon", hint: "The line where the earth or sea seems to meet the sky" },
    { word: "invisible", hint: "Not able to be seen" },
    { word: "jungle", hint: "A dense, tropical forest" },
    { word: "knowledge", hint: "Facts, information, and skills acquired by learning" },
    { word: "lightning", hint: "A sudden flash of light in the sky during a storm" },
    { word: "mountain", hint: "A large natural elevation of the earth's surface" },
    { word: "nebula", hint: "A cloud of gas and dust in space" },
    { word: "ocean", hint: "A large body of salt water that covers most of the earth" },
    { word: "pyramid", hint: "A monumental structure with a square base and triangular sides" },
    { word: "quicksand", hint: "A dangerous area of loose, wet sand that sucks objects down" },
    { word: "rainforest", hint: "A dense, tropical forest with high rainfall" },
    { word: "satellite", hint: "An object that orbits a planet or star" },
    { word: "telescope", hint: "An instrument for observing distant objects" },
    { word: "universe", hint: "All existing matter and space as a whole" },
    { word: "volcano", hint: "A mountain that erupts with lava and ash" },
    { word: "waterfall", hint: "A stream of water falling from a height" },
    { word: "xylophone", hint: "A musical instrument with wooden bars struck by mallets" },
    { word: "yacht", hint: "A medium-sized sailing boat used for recreation" },
    { word: "zephyr", hint: "A gentle, mild breeze" }
];
